### ISSUE TITLE
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'

### ISSUE THREAD

**Issue by robbyt** [gamechanger/dusty#416]
When I run the install script, it fails during the preflight check for docker-compose:

```
bash-4.3$ bash -c "`curl -L https://github.com/gamechanger/dusty/releases/download/0.2.2/install.sh`"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   391    0   391    0     0    732      0 --:--:-- --:--:-- --:--:--  3370
100  1266  100  1266    0     0   1792      0 --:--:-- --:--:-- --:--:--  1792
Downloading dusty binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379    0   379    0     0   3193      0 --:--:-- --:--:-- --:--:--  3239
100 6140k  100 6140k    0     0  4216k      0  0:00:01  0:00:01 --:--:-- 5517k
Authenticating as super user... needed to setup daemon
Resetting dusty daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   779  100   779    0     0   3595      0 --:--:-- --:--:-- --:--:--  3856
/Library/LaunchDaemons/com.gamechanger.dusty.plist: Could not find specified service
Testing dusty daemon's preflight...
2015-07-20 22:39:52 INFO:root Starting preflight check
2015-07-20 22:39:52 INFO:root Checking for required executables. PATH is /opt/local/bin:/opt/local/sbin:/Users/rterhaar/Documents/gocode/bin::/usr/local/bin:/usr/local/sbin/:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/go/bin:/Users/rterhaar/bin
2015-07-20 22:39:52 INFO:root Checking for existence of git
2015-07-20 22:39:52 INFO:root Checking for existence of nginx
2015-07-20 22:39:52 WARNING:py.warnings /tmp/_MEIyftU0a/dusty/preflight.py:42: UserWarning: Your nginx version (1.9.0) deviates from the supported version (1.8.0).

2015-07-20 22:39:52 INFO:root Checking for existence of rsync
2015-07-20 22:39:52 INFO:root Checking for existence of VBoxManage
2015-07-20 22:39:52 WARNING:py.warnings /tmp/_MEIyftU0a/dusty/preflight.py:42: UserWarning: Your virtualbox version (4.3.30) deviates from the supported version (4.3.26).

2015-07-20 22:39:52 INFO:root Checking for existence of boot2docker
2015-07-20 22:39:52 WARNING:py.warnings /tmp/_MEIyftU0a/dusty/preflight.py:42: UserWarning: Your boot2docker version (1.7.1) deviates from the supported version (1.7.0).

2015-07-20 22:39:52 INFO:root Checking for existence of docker
2015-07-20 22:39:52 WARNING:py.warnings /tmp/_MEIyftU0a/dusty/preflight.py:42: UserWarning: Your docker version (1.7.1) deviates from the supported version (1.7.0).

2015-07-20 22:39:52 INFO:root Checking for existence of docker-compose
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 37, in <module>
    import email.parser
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/utils.py", line 27, in <module>
    import random
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.cli", line 129, in main
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.daemon", line 110, in main
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.preflight", line 127, in preflight_check
dusty.preflight.PreflightException: Preflight Errors: 
	Command '['docker-compose', '--version']' returned non-zero exit status 1
Preflight failed; not loading daemon
```

I don't think the issue is with docker-compose, because it runs fine:
```
bash-4.3$ docker-compose --version
docker-compose version: 1.3.3
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
bash-4.3$ echo $?
0
```

**Comment by thieman** [comment]
That's odd, that stacktrace is coming purely from Compose when Dusty calls it (it's just calling a subprocess). What do you get for `which docker-compose` in a normal bash session? I'm wondering if you're pointing to the same Compose binary that Dusty is finding at `/usr/local/bin/docker-compose`.

Also, as an option, feel free to join us on Slack, this can be a bit nicer for involved technical back-and-forths https://dusty-slackin.herokuapp.com/

**Comment by robbyt** [comment]
Thanks for the fast response! 

Yes, please disregard this issue. It seems like there's something up with my docker-compose install and my python path.
